////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2025-09-03
//   .\svd2regs.py NVIC --svd .\ATSAMV71Q21B.svd --save .\nvic.rs

use kernel::utilities::StaticRef;
use kernel::utilities::registers::{self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly};
    
register_structs! {
    /// Nested Vectored Interrupt Controller
    NvicRegisters {
        /// Interrupt Set Enable Register n
        (0x000 => iser_0: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x004 => iser_1: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x008 => iser_2: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x00C => iser_3: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x010 => iser_4: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x014 => iser_5: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x018 => iser_6: ReadWrite<u32>),
        /// Interrupt Set Enable Register n
        (0x01C => iser_7: ReadWrite<u32>),
        (0x020 => _reserved0),
        /// Interrupt Clear Enable Register n
        (0x080 => icer_0: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x084 => icer_1: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x088 => icer_2: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x08C => icer_3: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x090 => icer_4: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x094 => icer_5: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x098 => icer_6: ReadWrite<u32>),
        /// Interrupt Clear Enable Register n
        (0x09C => icer_7: ReadWrite<u32>),
        (0x0A0 => _reserved1),
        /// Interrupt Set Pending Register n
        (0x100 => ispr_0: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x104 => ispr_1: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x108 => ispr_2: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x10C => ispr_3: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x110 => ispr_4: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x114 => ispr_5: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x118 => ispr_6: ReadWrite<u32>),
        /// Interrupt Set Pending Register n
        (0x11C => ispr_7: ReadWrite<u32>),
        (0x120 => _reserved2),
        /// Interrupt Clear Pending Register n
        (0x180 => icpr_0: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x184 => icpr_1: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x188 => icpr_2: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x18C => icpr_3: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x190 => icpr_4: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x194 => icpr_5: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x198 => icpr_6: ReadWrite<u32>),
        /// Interrupt Clear Pending Register n
        (0x19C => icpr_7: ReadWrite<u32>),
        (0x1A0 => _reserved3),
        /// Interrupt Active bit Register n
        (0x200 => iabr_0: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x204 => iabr_1: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x208 => iabr_2: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x20C => iabr_3: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x210 => iabr_4: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x214 => iabr_5: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x218 => iabr_6: ReadWrite<u32>),
        /// Interrupt Active bit Register n
        (0x21C => iabr_7: ReadWrite<u32>),
        (0x220 => _reserved4),
        /// Interrupt Priority Register (8Bit wide) n
        (0x300 => ip_0: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x301 => ip_1: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x302 => ip_2: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x303 => ip_3: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x304 => ip_4: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x305 => ip_5: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x306 => ip_6: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x307 => ip_7: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x308 => ip_8: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x309 => ip_9: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30A => ip_10: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30B => ip_11: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30C => ip_12: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30D => ip_13: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30E => ip_14: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x30F => ip_15: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x310 => ip_16: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x311 => ip_17: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x312 => ip_18: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x313 => ip_19: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x314 => ip_20: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x315 => ip_21: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x316 => ip_22: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x317 => ip_23: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x318 => ip_24: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x319 => ip_25: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31A => ip_26: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31B => ip_27: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31C => ip_28: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31D => ip_29: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31E => ip_30: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x31F => ip_31: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x320 => ip_32: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x321 => ip_33: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x322 => ip_34: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x323 => ip_35: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x324 => ip_36: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x325 => ip_37: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x326 => ip_38: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x327 => ip_39: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x328 => ip_40: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x329 => ip_41: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32A => ip_42: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32B => ip_43: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32C => ip_44: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32D => ip_45: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32E => ip_46: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x32F => ip_47: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x330 => ip_48: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x331 => ip_49: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x332 => ip_50: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x333 => ip_51: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x334 => ip_52: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x335 => ip_53: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x336 => ip_54: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x337 => ip_55: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x338 => ip_56: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x339 => ip_57: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33A => ip_58: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33B => ip_59: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33C => ip_60: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33D => ip_61: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33E => ip_62: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x33F => ip_63: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x340 => ip_64: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x341 => ip_65: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x342 => ip_66: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x343 => ip_67: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x344 => ip_68: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x345 => ip_69: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x346 => ip_70: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x347 => ip_71: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x348 => ip_72: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x349 => ip_73: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34A => ip_74: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34B => ip_75: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34C => ip_76: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34D => ip_77: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34E => ip_78: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x34F => ip_79: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x350 => ip_80: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x351 => ip_81: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x352 => ip_82: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x353 => ip_83: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x354 => ip_84: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x355 => ip_85: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x356 => ip_86: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x357 => ip_87: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x358 => ip_88: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x359 => ip_89: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35A => ip_90: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35B => ip_91: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35C => ip_92: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35D => ip_93: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35E => ip_94: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x35F => ip_95: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x360 => ip_96: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x361 => ip_97: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x362 => ip_98: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x363 => ip_99: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x364 => ip_100: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x365 => ip_101: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x366 => ip_102: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x367 => ip_103: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x368 => ip_104: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x369 => ip_105: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36A => ip_106: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36B => ip_107: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36C => ip_108: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36D => ip_109: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36E => ip_110: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x36F => ip_111: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x370 => ip_112: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x371 => ip_113: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x372 => ip_114: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x373 => ip_115: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x374 => ip_116: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x375 => ip_117: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x376 => ip_118: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x377 => ip_119: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x378 => ip_120: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x379 => ip_121: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37A => ip_122: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37B => ip_123: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37C => ip_124: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37D => ip_125: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37E => ip_126: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x37F => ip_127: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x380 => ip_128: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x381 => ip_129: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x382 => ip_130: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x383 => ip_131: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x384 => ip_132: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x385 => ip_133: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x386 => ip_134: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x387 => ip_135: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x388 => ip_136: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x389 => ip_137: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38A => ip_138: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38B => ip_139: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38C => ip_140: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38D => ip_141: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38E => ip_142: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x38F => ip_143: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x390 => ip_144: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x391 => ip_145: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x392 => ip_146: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x393 => ip_147: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x394 => ip_148: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x395 => ip_149: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x396 => ip_150: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x397 => ip_151: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x398 => ip_152: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x399 => ip_153: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39A => ip_154: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39B => ip_155: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39C => ip_156: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39D => ip_157: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39E => ip_158: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x39F => ip_159: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A0 => ip_160: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A1 => ip_161: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A2 => ip_162: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A3 => ip_163: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A4 => ip_164: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A5 => ip_165: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A6 => ip_166: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A7 => ip_167: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A8 => ip_168: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3A9 => ip_169: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AA => ip_170: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AB => ip_171: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AC => ip_172: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AD => ip_173: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AE => ip_174: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3AF => ip_175: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B0 => ip_176: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B1 => ip_177: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B2 => ip_178: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B3 => ip_179: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B4 => ip_180: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B5 => ip_181: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B6 => ip_182: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B7 => ip_183: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B8 => ip_184: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3B9 => ip_185: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BA => ip_186: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BB => ip_187: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BC => ip_188: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BD => ip_189: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BE => ip_190: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3BF => ip_191: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C0 => ip_192: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C1 => ip_193: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C2 => ip_194: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C3 => ip_195: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C4 => ip_196: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C5 => ip_197: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C6 => ip_198: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C7 => ip_199: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C8 => ip_200: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3C9 => ip_201: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CA => ip_202: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CB => ip_203: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CC => ip_204: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CD => ip_205: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CE => ip_206: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3CF => ip_207: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D0 => ip_208: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D1 => ip_209: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D2 => ip_210: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D3 => ip_211: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D4 => ip_212: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D5 => ip_213: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D6 => ip_214: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D7 => ip_215: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D8 => ip_216: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3D9 => ip_217: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DA => ip_218: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DB => ip_219: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DC => ip_220: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DD => ip_221: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DE => ip_222: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3DF => ip_223: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E0 => ip_224: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E1 => ip_225: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E2 => ip_226: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E3 => ip_227: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E4 => ip_228: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E5 => ip_229: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E6 => ip_230: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E7 => ip_231: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E8 => ip_232: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3E9 => ip_233: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3EA => ip_234: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3EB => ip_235: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3EC => ip_236: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3ED => ip_237: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3EE => ip_238: ReadWrite<u8>),
        /// Interrupt Priority Register (8Bit wide) n
        (0x3EF => ip_239: ReadWrite<u8>),
        (0x3F0 => _reserved5),
        /// Software Trigger Interrupt Register
        (0xE00 => stir: WriteOnly<u32>),
        (0xE04 => @END),
    }
}
register_bitfields![u32,
STIR [
    /// Interrupt ID of the interrupt to trigger, in the range 0-239. For example, a value of 0x03 specifies interrupt IRQ3.
    INTID OFFSET(0) NUMBITS(9) []
],
ISER[0] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[1] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[2] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[3] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[4] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[5] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[6] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ISER[7] [
    /// Interrupt set enable bits
    SETENA OFFSET(0) NUMBITS(32) []
],
ICER[0] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[1] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[2] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[3] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[4] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[5] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[6] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ICER[7] [
    /// Interrupt clear-enable bits
    CLRENA OFFSET(0) NUMBITS(32) []
],
ISPR[0] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[1] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[2] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[3] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[4] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[5] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[6] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ISPR[7] [
    /// Interrupt set-pending bits
    SETPEND OFFSET(0) NUMBITS(32) []
],
ICPR[0] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[1] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[2] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[3] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[4] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[5] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[6] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
ICPR[7] [
    /// Interrupt clear-pending bits
    CLRPEND OFFSET(0) NUMBITS(32) []
],
IABR[0] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[1] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[2] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[3] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[4] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[5] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[6] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IABR[7] [
    /// Interrupt active flags
    ACTIVE OFFSET(0) NUMBITS(32) []
],
IP[0] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[1] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[2] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[3] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[4] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[5] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[6] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[7] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[8] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[9] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[10] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[11] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[12] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[13] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[14] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[15] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[16] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[17] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[18] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[19] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[20] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[21] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[22] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[23] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[24] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[25] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[26] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[27] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[28] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[29] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[30] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[31] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[32] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[33] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[34] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[35] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[36] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[37] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[38] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[39] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[40] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[41] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[42] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[43] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[44] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[45] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[46] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[47] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[48] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[49] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[50] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[51] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[52] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[53] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[54] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[55] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[56] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[57] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[58] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[59] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[60] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[61] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[62] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[63] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[64] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[65] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[66] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[67] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[68] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[69] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[70] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[71] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[72] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[73] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[74] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[75] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[76] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[77] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[78] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[79] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[80] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[81] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[82] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[83] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[84] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[85] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[86] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[87] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[88] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[89] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[90] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[91] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[92] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[93] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[94] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[95] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[96] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[97] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[98] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[99] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[100] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[101] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[102] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[103] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[104] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[105] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[106] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[107] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[108] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[109] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[110] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[111] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[112] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[113] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[114] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[115] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[116] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[117] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[118] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[119] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[120] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[121] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[122] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[123] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[124] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[125] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[126] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[127] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[128] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[129] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[130] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[131] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[132] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[133] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[134] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[135] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[136] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[137] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[138] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[139] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[140] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[141] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[142] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[143] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[144] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[145] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[146] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[147] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[148] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[149] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[150] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[151] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[152] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[153] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[154] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[155] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[156] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[157] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[158] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[159] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[160] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[161] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[162] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[163] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[164] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[165] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[166] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[167] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[168] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[169] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[170] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[171] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[172] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[173] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[174] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[175] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[176] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[177] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[178] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[179] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[180] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[181] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[182] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[183] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[184] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[185] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[186] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[187] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[188] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[189] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[190] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[191] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[192] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[193] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[194] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[195] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[196] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[197] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[198] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[199] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[200] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[201] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[202] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[203] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[204] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[205] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[206] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[207] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[208] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[209] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[210] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[211] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[212] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[213] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[214] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[215] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[216] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[217] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[218] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[219] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[220] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[221] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[222] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[223] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[224] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[225] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[226] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[227] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[228] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[229] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[230] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[231] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[232] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[233] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[234] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[235] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[236] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[237] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[238] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
],
IP[239] [
    /// Priority of interrupt 0
    PRI0 OFFSET(0) NUMBITS(8) []
]
];
const NVIC_BASE: StaticRef<NvicRegisters> =
    unsafe { StaticRef::new(0xE000E100 as *const NvicRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

