////////////////////////////////////////////////////////////////////////////////
// Autogenerated by svd2regs.py on 2025-12-27
//   svd2regs.py --svd ATSAMV71Q21B.svd --save pmc.rs PMC

use kernel::utilities::StaticRef;
use kernel::utilities::registers::{self, register_bitfields, register_structs, ReadOnly, ReadWrite, WriteOnly};
    
register_structs! {
    /// Power Management Controller
    PmcRegisters {
        /// System Clock Enable Register
        (0x000 => scer: WriteOnly<u32, SCER::Register>),
        /// System Clock Disable Register
        (0x004 => scdr: WriteOnly<u32, SCDR::Register>),
        /// System Clock Status Register
        (0x008 => scsr: ReadOnly<u32, SCSR::Register>),
        (0x00C => _reserved0),
        /// Peripheral Clock Enable Register 0
        (0x010 => pcer0: WriteOnly<u32, PCER0::Register>),
        /// Peripheral Clock Disable Register 0
        (0x014 => pcdr0: WriteOnly<u32, PCDR0::Register>),
        /// Peripheral Clock Status Register 0
        (0x018 => pcsr0: ReadOnly<u32, PCSR0::Register>),
        /// UTMI Clock Register
        (0x01C => ckgr_uckr: ReadWrite<u32, CKGR_UCKR::Register>),
        /// Main Oscillator Register
        (0x020 => ckgr_mor: ReadWrite<u32, CKGR_MOR::Register>),
        /// Main Clock Frequency Register
        (0x024 => ckgr_mcfr: ReadWrite<u32, CKGR_MCFR::Register>),
        /// PLLA Register
        (0x028 => ckgr_pllar: ReadWrite<u32, CKGR_PLLAR::Register>),
        (0x02C => _reserved1),
        /// Master Clock Register
        (0x030 => mckr: ReadWrite<u32, MCKR::Register>),
        (0x034 => _reserved2),
        /// USB Clock Register
        (0x038 => usb: ReadWrite<u32, USB::Register>),
        (0x03C => _reserved3),
        /// Programmable Clock Register
        (0x040 => pck_0: ReadWrite<u32, PCK[0]::Register>),
        /// Programmable Clock Register
        (0x044 => pck_1: ReadWrite<u32, PCK[1]::Register>),
        /// Programmable Clock Register
        (0x048 => pck_2: ReadWrite<u32, PCK[2]::Register>),
        /// Programmable Clock Register
        (0x04C => pck_3: ReadWrite<u32, PCK[3]::Register>),
        /// Programmable Clock Register
        (0x050 => pck_4: ReadWrite<u32, PCK[4]::Register>),
        /// Programmable Clock Register
        (0x054 => pck_5: ReadWrite<u32, PCK[5]::Register>),
        /// Programmable Clock Register
        (0x058 => pck_6: ReadWrite<u32, PCK[6]::Register>),
        /// Programmable Clock Register
        (0x05C => pck_7: ReadWrite<u32, PCK[7]::Register>),
        /// Interrupt Enable Register
        (0x060 => ier: WriteOnly<u32, IER::Register>),
        /// Interrupt Disable Register
        (0x064 => idr: WriteOnly<u32, IDR::Register>),
        /// Status Register
        (0x068 => sr: ReadOnly<u32, SR::Register>),
        /// Interrupt Mask Register
        (0x06C => imr: ReadOnly<u32, IMR::Register>),
        /// Fast Startup Mode Register
        (0x070 => fsmr: ReadWrite<u32, FSMR::Register>),
        /// Fast Startup Polarity Register
        (0x074 => fspr: ReadWrite<u32, FSPR::Register>),
        /// Fault Output Clear Register
        (0x078 => focr: WriteOnly<u32>),
        (0x07C => _reserved4),
        /// Write Protection Mode Register
        (0x0E4 => wpmr: ReadWrite<u32, WPMR::Register>),
        /// Write Protection Status Register
        (0x0E8 => wpsr: ReadOnly<u32, WPSR::Register>),
        (0x0EC => _reserved5),
        /// Peripheral Clock Enable Register 1
        (0x100 => pcer1: WriteOnly<u32, PCER1::Register>),
        /// Peripheral Clock Disable Register 1
        (0x104 => pcdr1: WriteOnly<u32, PCDR1::Register>),
        /// Peripheral Clock Status Register 1
        (0x108 => pcsr1: ReadOnly<u32, PCSR1::Register>),
        /// Peripheral Control Register
        (0x10C => pcr: ReadWrite<u32, PCR::Register>),
        /// Oscillator Calibration Register
        (0x110 => ocr: ReadWrite<u32, OCR::Register>),
        /// SleepWalking Enable Register 0
        (0x114 => slpwk_er0: WriteOnly<u32, SLPWK_ER0::Register>),
        /// SleepWalking Disable Register 0
        (0x118 => slpwk_dr0: WriteOnly<u32, SLPWK_DR0::Register>),
        /// SleepWalking Status Register 0
        (0x11C => slpwk_sr0: ReadOnly<u32, SLPWK_SR0::Register>),
        /// SleepWalking Activity Status Register 0
        (0x120 => slpwk_asr0: ReadOnly<u32, SLPWK_ASR0::Register>),
        (0x124 => _reserved6),
        /// PLL Maximum Multiplier Value Register
        (0x130 => pmmr: ReadWrite<u32>),
        /// SleepWalking Enable Register 1
        (0x134 => slpwk_er1: WriteOnly<u32, SLPWK_ER1::Register>),
        /// SleepWalking Disable Register 1
        (0x138 => slpwk_dr1: WriteOnly<u32, SLPWK_DR1::Register>),
        /// SleepWalking Status Register 1
        (0x13C => slpwk_sr1: ReadOnly<u32, SLPWK_SR1::Register>),
        /// SleepWalking Activity Status Register 1
        (0x140 => slpwk_asr1: ReadOnly<u32, SLPWK_ASR1::Register>),
        /// SleepWalking Activity In Progress Register
        (0x144 => slpwk_aipr: ReadOnly<u32>),
        (0x148 => @END),
    }
}
register_bitfields![u32,
SCER [
    /// Enable USB FS Clock
    USBCLK OFFSET(5) NUMBITS(1) [],
    /// Programmable Clock 0 Output Enable
    PCK0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock 1 Output Enable
    PCK1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock 2 Output Enable
    PCK2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock 3 Output Enable
    PCK3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock 4 Output Enable
    PCK4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock 5 Output Enable
    PCK5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock 6 Output Enable
    PCK6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock 7 Output Enable
    PCK7 OFFSET(15) NUMBITS(1) []
],
SCDR [
    /// Disable USB FS Clock
    USBCLK OFFSET(5) NUMBITS(1) [],
    /// Programmable Clock 0 Output Disable
    PCK0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock 1 Output Disable
    PCK1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock 2 Output Disable
    PCK2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock 3 Output Disable
    PCK3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock 4 Output Disable
    PCK4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock 5 Output Disable
    PCK5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock 6 Output Disable
    PCK6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock 7 Output Disable
    PCK7 OFFSET(15) NUMBITS(1) []
],
SCSR [
    /// HCLK Status
    HCLKS OFFSET(0) NUMBITS(1) [],
    /// USB FS Clock Status
    USBCLK OFFSET(5) NUMBITS(1) [],
    /// Programmable Clock 0 Output Status
    PCK0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock 1 Output Status
    PCK1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock 2 Output Status
    PCK2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock 3 Output Status
    PCK3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock 4 Output Status
    PCK4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock 5 Output Status
    PCK5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock 6 Output Status
    PCK6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock 7 Output Status
    PCK7 OFFSET(15) NUMBITS(1) []
],
PCER0 [
    /// Peripheral Clock 7 Enable
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 8 Enable
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 9 Enable
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 10 Enable
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 11 Enable
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 12 Enable
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 13 Enable
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 14 Enable
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 15 Enable
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 16 Enable
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 17 Enable
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 18 Enable
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 19 Enable
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 20 Enable
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 21 Enable
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 22 Enable
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral Clock 23 Enable
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral Clock 24 Enable
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 25 Enable
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 26 Enable
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 27 Enable
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 28 Enable
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral Clock 29 Enable
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral Clock 30 Enable
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral Clock 31 Enable
    PID31 OFFSET(31) NUMBITS(1) []
],
PCDR0 [
    /// Peripheral Clock 7 Disable
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 8 Disable
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 9 Disable
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 10 Disable
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 11 Disable
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 12 Disable
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 13 Disable
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 14 Disable
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 15 Disable
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 16 Disable
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 17 Disable
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 18 Disable
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 19 Disable
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 20 Disable
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 21 Disable
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 22 Disable
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral Clock 23 Disable
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral Clock 24 Disable
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 25 Disable
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 26 Disable
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 27 Disable
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 28 Disable
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral Clock 29 Disable
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral Clock 30 Disable
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral Clock 31 Disable
    PID31 OFFSET(31) NUMBITS(1) []
],
PCSR0 [
    /// Peripheral Clock 7 Status
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 8 Status
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 9 Status
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 10 Status
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 11 Status
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 12 Status
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 13 Status
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 14 Status
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 15 Status
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 16 Status
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 17 Status
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 18 Status
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 19 Status
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 20 Status
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 21 Status
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 22 Status
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral Clock 23 Status
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral Clock 24 Status
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 25 Status
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 26 Status
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 27 Status
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 28 Status
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral Clock 29 Status
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral Clock 30 Status
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral Clock 31 Status
    PID31 OFFSET(31) NUMBITS(1) []
],
CKGR_UCKR [
    /// UTMI PLL Enable
    UPLLEN OFFSET(16) NUMBITS(1) [],
    /// UTMI PLL Start-up Time
    UPLLCOUNT OFFSET(20) NUMBITS(4) []
],
CKGR_MOR [
    /// Main Crystal Oscillator Enable
    MOSCXTEN OFFSET(0) NUMBITS(1) [],
    /// Main Crystal Oscillator Bypass
    MOSCXTBY OFFSET(1) NUMBITS(1) [],
    /// Wait Mode Command (Write-only)
    WAITMODE OFFSET(2) NUMBITS(1) [],
    /// Main RC Oscillator Enable
    MOSCRCEN OFFSET(3) NUMBITS(1) [],
    /// Main RC Oscillator Frequency Selection
    MOSCRCF OFFSET(4) NUMBITS(3) [
        /// The RC oscillator frequency is at 4 MHz
        TheRCOscillatorFrequencyIsAt4MHz = 0,
        /// The RC oscillator frequency is at 8 MHz
        TheRCOscillatorFrequencyIsAt8MHz = 1,
        /// The RC oscillator frequency is at 12 MHz
        TheRCOscillatorFrequencyIsAt12MHz = 2
    ],
    /// Main Crystal Oscillator Startup Time
    MOSCXTST OFFSET(8) NUMBITS(8) [],
    /// Write Access Password
    KEY OFFSET(16) NUMBITS(8) [
        /// Writing any other value in this field aborts the write operation.Always reads as 0.
        WritingAnyOtherValueInThisFieldAbortsTheWriteOperationAlwaysReadsAs0 = 55
    ],
    /// Main Clock Oscillator Selection
    MOSCSEL OFFSET(24) NUMBITS(1) [],
    /// Clock Failure Detector Enable
    CFDEN OFFSET(25) NUMBITS(1) [],
    /// 32.768 kHz Crystal Oscillator Frequency Monitoring Enable
    XT32KFME OFFSET(26) NUMBITS(1) []
],
CKGR_MCFR [
    /// Main Clock Frequency
    MAINF OFFSET(0) NUMBITS(16) [],
    /// Main Clock Frequency Measure Ready
    MAINFRDY OFFSET(16) NUMBITS(1) [],
    /// RC Oscillator Frequency Measure (write-only)
    RCMEAS OFFSET(20) NUMBITS(1) [],
    /// Counter Clock Source Selection
    CCSS OFFSET(24) NUMBITS(1) []
],
CKGR_PLLAR [
    /// PLLA Front End Divider
    DIVA OFFSET(0) NUMBITS(8) [
        /// Divider output is 0 and PLLA is disabled.
        DividerOutputIs0AndPLLAIsDisabled = 0,
        /// Divider is bypassed (divide by 1) and PLLA is enabled.
        DividerIsBypassedDivideBy1AndPLLAIsEnabled = 1
    ],
    /// PLLA Counter
    PLLACOUNT OFFSET(8) NUMBITS(6) [],
    /// PLLA Multiplier
    MULA OFFSET(16) NUMBITS(11) [],
    /// Must Be Set to 1
    ONE OFFSET(29) NUMBITS(1) []
],
MCKR [
    /// Master Clock Source Selection
    CSS OFFSET(0) NUMBITS(2) [
        /// Slow Clock is selected
        SlowClockIsSelected = 0,
        /// Main Clock is selected
        MainClockIsSelected = 1,
        /// PLLA Clock is selected
        PLLAClockIsSelected = 2,
        /// Divided UPLL Clock is selected
        DividedUPLLClockIsSelected = 3
    ],
    /// Processor Clock Prescaler
    PRES OFFSET(4) NUMBITS(3) [
        /// Selected clock
        SelectedClock = 0,
        /// Selected clock divided by 2
        SelectedClockDividedBy2 = 1,
        /// Selected clock divided by 4
        SelectedClockDividedBy4 = 2,
        /// Selected clock divided by 8
        SelectedClockDividedBy8 = 3,
        /// Selected clock divided by 16
        SelectedClockDividedBy16 = 4,
        /// Selected clock divided by 32
        SelectedClockDividedBy32 = 5,
        /// Selected clock divided by 64
        SelectedClockDividedBy64 = 6,
        /// Selected clock divided by 3
        SelectedClockDividedBy3 = 7
    ],
    /// Master Clock Division
    MDIV OFFSET(8) NUMBITS(2) [
        /// Master Clock is Prescaler Output Clock divided by 1.
        MasterClockIsPrescalerOutputClockDividedBy1 = 0,
        /// Master Clock is Prescaler Output Clock divided by 2.
        MasterClockIsPrescalerOutputClockDividedBy2 = 1,
        /// Master Clock is Prescaler Output Clock divided by 4.
        MasterClockIsPrescalerOutputClockDividedBy4 = 2,
        /// Master Clock is Prescaler Output Clock divided by 3.
        MasterClockIsPrescalerOutputClockDividedBy3 = 3
    ],
    /// UPLL Divider by 2
    UPLLDIV2 OFFSET(13) NUMBITS(1) []
],
USB [
    /// USB Input Clock Selection
    USBS OFFSET(0) NUMBITS(1) [],
    /// Divider for USB_48M
    USBDIV OFFSET(8) NUMBITS(4) []
],
IER [
    /// Main Crystal Oscillator Status Interrupt Enable
    MOSCXTS OFFSET(0) NUMBITS(1) [],
    /// PLLA Lock Interrupt Enable
    LOCKA OFFSET(1) NUMBITS(1) [],
    /// Master Clock Ready Interrupt Enable
    MCKRDY OFFSET(3) NUMBITS(1) [],
    /// UTMI PLL Lock Interrupt Enable
    LOCKU OFFSET(6) NUMBITS(1) [],
    /// Programmable Clock Ready 0 Interrupt Enable
    PCKRDY0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock Ready 1 Interrupt Enable
    PCKRDY1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock Ready 2 Interrupt Enable
    PCKRDY2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock Ready 3 Interrupt Enable
    PCKRDY3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock Ready 4 Interrupt Enable
    PCKRDY4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock Ready 5 Interrupt Enable
    PCKRDY5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock Ready 6 Interrupt Enable
    PCKRDY6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock Ready 7 Interrupt Enable
    PCKRDY7 OFFSET(15) NUMBITS(1) [],
    /// Main Clock Source Oscillator Selection Status Interrupt Enable
    MOSCSELS OFFSET(16) NUMBITS(1) [],
    /// Main RC Oscillator Status Interrupt Enable
    MOSCRCS OFFSET(17) NUMBITS(1) [],
    /// Clock Failure Detector Event Interrupt Enable
    CFDEV OFFSET(18) NUMBITS(1) [],
    /// 32.768 kHz Crystal Oscillator Error Interrupt Enable
    XT32KERR OFFSET(21) NUMBITS(1) []
],
IDR [
    /// Main Crystal Oscillator Status Interrupt Disable
    MOSCXTS OFFSET(0) NUMBITS(1) [],
    /// PLLA Lock Interrupt Disable
    LOCKA OFFSET(1) NUMBITS(1) [],
    /// Master Clock Ready Interrupt Disable
    MCKRDY OFFSET(3) NUMBITS(1) [],
    /// UTMI PLL Lock Interrupt Disable
    LOCKU OFFSET(6) NUMBITS(1) [],
    /// Programmable Clock Ready 0 Interrupt Disable
    PCKRDY0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock Ready 1 Interrupt Disable
    PCKRDY1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock Ready 2 Interrupt Disable
    PCKRDY2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock Ready 3 Interrupt Disable
    PCKRDY3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock Ready 4 Interrupt Disable
    PCKRDY4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock Ready 5 Interrupt Disable
    PCKRDY5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock Ready 6 Interrupt Disable
    PCKRDY6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock Ready 7 Interrupt Disable
    PCKRDY7 OFFSET(15) NUMBITS(1) [],
    /// Main Clock Source Oscillator Selection Status Interrupt Disable
    MOSCSELS OFFSET(16) NUMBITS(1) [],
    /// Main RC Status Interrupt Disable
    MOSCRCS OFFSET(17) NUMBITS(1) [],
    /// Clock Failure Detector Event Interrupt Disable
    CFDEV OFFSET(18) NUMBITS(1) [],
    /// 32.768 kHz Crystal Oscillator Error Interrupt Disable
    XT32KERR OFFSET(21) NUMBITS(1) []
],
SR [
    /// Main Crystal Oscillator Status
    MOSCXTS OFFSET(0) NUMBITS(1) [],
    /// PLLA Lock Status
    LOCKA OFFSET(1) NUMBITS(1) [],
    /// Master Clock Status
    MCKRDY OFFSET(3) NUMBITS(1) [],
    /// UTMI PLL Lock Status
    LOCKU OFFSET(6) NUMBITS(1) [],
    /// Slow Clock Source Oscillator Selection
    OSCSELS OFFSET(7) NUMBITS(1) [],
    /// Programmable Clock Ready 0 Status
    PCKRDY0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock Ready 1 Status
    PCKRDY1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock Ready 2 Status
    PCKRDY2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock Ready 3 Status
    PCKRDY3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock Ready 4 Status
    PCKRDY4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock Ready 5 Status
    PCKRDY5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock Ready 6 Status
    PCKRDY6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock Ready 7 Status
    PCKRDY7 OFFSET(15) NUMBITS(1) [],
    /// Main Clock Source Oscillator Selection Status
    MOSCSELS OFFSET(16) NUMBITS(1) [],
    /// Main RC Oscillator Status
    MOSCRCS OFFSET(17) NUMBITS(1) [],
    /// Clock Failure Detector Event
    CFDEV OFFSET(18) NUMBITS(1) [],
    /// Clock Failure Detector Status
    CFDS OFFSET(19) NUMBITS(1) [],
    /// Clock Failure Detector Fault Output Status
    FOS OFFSET(20) NUMBITS(1) [],
    /// Slow Crystal Oscillator Error
    XT32KERR OFFSET(21) NUMBITS(1) []
],
IMR [
    /// Main Crystal Oscillator Status Interrupt Mask
    MOSCXTS OFFSET(0) NUMBITS(1) [],
    /// PLLA Lock Interrupt Mask
    LOCKA OFFSET(1) NUMBITS(1) [],
    /// Master Clock Ready Interrupt Mask
    MCKRDY OFFSET(3) NUMBITS(1) [],
    /// UTMI PLL Lock Interrupt Mask
    LOCKU OFFSET(6) NUMBITS(1) [],
    /// Programmable Clock Ready 0 Interrupt Mask
    PCKRDY0 OFFSET(8) NUMBITS(1) [],
    /// Programmable Clock Ready 1 Interrupt Mask
    PCKRDY1 OFFSET(9) NUMBITS(1) [],
    /// Programmable Clock Ready 2 Interrupt Mask
    PCKRDY2 OFFSET(10) NUMBITS(1) [],
    /// Programmable Clock Ready 3 Interrupt Mask
    PCKRDY3 OFFSET(11) NUMBITS(1) [],
    /// Programmable Clock Ready 4 Interrupt Mask
    PCKRDY4 OFFSET(12) NUMBITS(1) [],
    /// Programmable Clock Ready 5 Interrupt Mask
    PCKRDY5 OFFSET(13) NUMBITS(1) [],
    /// Programmable Clock Ready 6 Interrupt Mask
    PCKRDY6 OFFSET(14) NUMBITS(1) [],
    /// Programmable Clock Ready 7 Interrupt Mask
    PCKRDY7 OFFSET(15) NUMBITS(1) [],
    /// Main Clock Source Oscillator Selection Status Interrupt Mask
    MOSCSELS OFFSET(16) NUMBITS(1) [],
    /// Main RC Status Interrupt Mask
    MOSCRCS OFFSET(17) NUMBITS(1) [],
    /// Clock Failure Detector Event Interrupt Mask
    CFDEV OFFSET(18) NUMBITS(1) [],
    /// 32.768 kHz Crystal Oscillator Error Interrupt Mask
    XT32KERR OFFSET(21) NUMBITS(1) []
],
FSMR [
    /// Fast Startup Input Enable 0
    FSTT0 OFFSET(0) NUMBITS(1) [],
    /// Fast Startup Input Enable 1
    FSTT1 OFFSET(1) NUMBITS(1) [],
    /// Fast Startup Input Enable 2
    FSTT2 OFFSET(2) NUMBITS(1) [],
    /// Fast Startup Input Enable 3
    FSTT3 OFFSET(3) NUMBITS(1) [],
    /// Fast Startup Input Enable 4
    FSTT4 OFFSET(4) NUMBITS(1) [],
    /// Fast Startup Input Enable 5
    FSTT5 OFFSET(5) NUMBITS(1) [],
    /// Fast Startup Input Enable 6
    FSTT6 OFFSET(6) NUMBITS(1) [],
    /// Fast Startup Input Enable 7
    FSTT7 OFFSET(7) NUMBITS(1) [],
    /// Fast Startup Input Enable 8
    FSTT8 OFFSET(8) NUMBITS(1) [],
    /// Fast Startup Input Enable 9
    FSTT9 OFFSET(9) NUMBITS(1) [],
    /// Fast Startup Input Enable 10
    FSTT10 OFFSET(10) NUMBITS(1) [],
    /// Fast Startup Input Enable 11
    FSTT11 OFFSET(11) NUMBITS(1) [],
    /// Fast Startup Input Enable 12
    FSTT12 OFFSET(12) NUMBITS(1) [],
    /// Fast Startup Input Enable 13
    FSTT13 OFFSET(13) NUMBITS(1) [],
    /// Fast Startup Input Enable 14
    FSTT14 OFFSET(14) NUMBITS(1) [],
    /// Fast Startup Input Enable 15
    FSTT15 OFFSET(15) NUMBITS(1) [],
    /// RTT Alarm Enable
    RTTAL OFFSET(16) NUMBITS(1) [],
    /// RTC Alarm Enable
    RTCAL OFFSET(17) NUMBITS(1) [],
    /// USB Alarm Enable
    USBAL OFFSET(18) NUMBITS(1) [],
    /// Low-power Mode
    LPM OFFSET(20) NUMBITS(1) [],
    /// Flash Low-power Mode
    FLPM OFFSET(21) NUMBITS(2) [
        /// Flash is in Standby Mode when system enters Wait Mode
        FlashIsInStandbyModeWhenSystemEntersWaitMode = 0,
        /// Flash is in Deep-power-down mode when system enters Wait Mode
        FlashIsInDeepPowerDownModeWhenSystemEntersWaitMode = 1,
        /// Idle mode
        IdleMode = 2
    ],
    /// Force Flash Low-power Mode
    FFLPM OFFSET(23) NUMBITS(1) []
],
FSPR [
    /// Fast Startup Input Polarity 0
    FSTP0 OFFSET(0) NUMBITS(1) [],
    /// Fast Startup Input Polarity 1
    FSTP1 OFFSET(1) NUMBITS(1) [],
    /// Fast Startup Input Polarity 2
    FSTP2 OFFSET(2) NUMBITS(1) [],
    /// Fast Startup Input Polarity 3
    FSTP3 OFFSET(3) NUMBITS(1) [],
    /// Fast Startup Input Polarity 4
    FSTP4 OFFSET(4) NUMBITS(1) [],
    /// Fast Startup Input Polarity 5
    FSTP5 OFFSET(5) NUMBITS(1) [],
    /// Fast Startup Input Polarity 6
    FSTP6 OFFSET(6) NUMBITS(1) [],
    /// Fast Startup Input Polarity 7
    FSTP7 OFFSET(7) NUMBITS(1) [],
    /// Fast Startup Input Polarity 8
    FSTP8 OFFSET(8) NUMBITS(1) [],
    /// Fast Startup Input Polarity 9
    FSTP9 OFFSET(9) NUMBITS(1) [],
    /// Fast Startup Input Polarity 10
    FSTP10 OFFSET(10) NUMBITS(1) [],
    /// Fast Startup Input Polarity 11
    FSTP11 OFFSET(11) NUMBITS(1) [],
    /// Fast Startup Input Polarity 12
    FSTP12 OFFSET(12) NUMBITS(1) [],
    /// Fast Startup Input Polarity 13
    FSTP13 OFFSET(13) NUMBITS(1) [],
    /// Fast Startup Input Polarity 14
    FSTP14 OFFSET(14) NUMBITS(1) [],
    /// Fast Startup Input Polarity 15
    FSTP15 OFFSET(15) NUMBITS(1) []
],
FOCR [
    /// Fault Output Clear
    FOCLR OFFSET(0) NUMBITS(1) []
],
WPMR [
    /// Write Protection Enable
    WPEN OFFSET(0) NUMBITS(1) [],
    /// Write Protection Key
    WPKEY OFFSET(8) NUMBITS(24) [
        /// Writing any other value in this field aborts the write operation of the WPEN bit. Always reads as 0.
        PASSWD = 5262659
    ]
],
WPSR [
    /// Write Protection Violation Status
    WPVS OFFSET(0) NUMBITS(1) [],
    /// Write Protection Violation Source
    WPVSRC OFFSET(8) NUMBITS(16) []
],
PCER1 [
    /// Peripheral Clock 32 Enable
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral Clock 33 Enable
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral Clock 34 Enable
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral Clock 35 Enable
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral Clock 37 Enable
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral Clock 39 Enable
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 40 Enable
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 41 Enable
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 42 Enable
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 43 Enable
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 44 Enable
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 45 Enable
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 46 Enable
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 47 Enable
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 48 Enable
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 49 Enable
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 50 Enable
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 51 Enable
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 52 Enable
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 53 Enable
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 56 Enable
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 57 Enable
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 58 Enable
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 59 Enable
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 60 Enable
    PID60 OFFSET(28) NUMBITS(1) []
],
PCDR1 [
    /// Peripheral Clock 32 Disable
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral Clock 33 Disable
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral Clock 34 Disable
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral Clock 35 Disable
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral Clock 37 Disable
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral Clock 39 Disable
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 40 Disable
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 41 Disable
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 42 Disable
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 43 Disable
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 44 Disable
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 45 Disable
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 46 Disable
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 47 Disable
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 48 Disable
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 49 Disable
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 50 Disable
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 51 Disable
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 52 Disable
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 53 Disable
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 56 Disable
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 57 Disable
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 58 Disable
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 59 Disable
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 60 Disable
    PID60 OFFSET(28) NUMBITS(1) []
],
PCSR1 [
    /// Peripheral Clock 32 Status
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral Clock 33 Status
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral Clock 34 Status
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral Clock 35 Status
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral Clock 37 Status
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral Clock 39 Status
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral Clock 40 Status
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral Clock 41 Status
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral Clock 42 Status
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral Clock 43 Status
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral Clock 44 Status
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral Clock 45 Status
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral Clock 46 Status
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral Clock 47 Status
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral Clock 48 Status
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral Clock 49 Status
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral Clock 50 Status
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral Clock 51 Status
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral Clock 52 Status
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral Clock 53 Status
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral Clock 56 Status
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral Clock 57 Status
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral Clock 58 Status
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral Clock 59 Status
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral Clock 60 Status
    PID60 OFFSET(28) NUMBITS(1) []
],
PCR [
    /// Peripheral ID
    PID OFFSET(0) NUMBITS(7) [],
    /// Generic Clock Source Selection
    GCLKCSS OFFSET(8) NUMBITS(3) [
        /// Slow clock is selected
        SlowClockIsSelected = 0,
        /// Main clock is selected
        MainClockIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLL Clock is selected
        UPLLClockIsSelected = 3,
        /// Master Clock is selected
        MasterClockIsSelected = 4
    ],
    /// Command
    CMD OFFSET(12) NUMBITS(1) [],
    /// Generic Clock Division Ratio
    GCLKDIV OFFSET(20) NUMBITS(8) [],
    /// Enable
    EN OFFSET(28) NUMBITS(1) [],
    /// Generic Clock Enable
    GCLKEN OFFSET(29) NUMBITS(1) []
],
OCR [
    /// Main RC Oscillator Calibration Bits for 4 MHz
    CAL4 OFFSET(0) NUMBITS(7) [],
    /// Selection of Main RC Oscillator Calibration Bits for 4 MHz
    SEL4 OFFSET(7) NUMBITS(1) [],
    /// Main RC Oscillator Calibration Bits for 8 MHz
    CAL8 OFFSET(8) NUMBITS(7) [],
    /// Selection of Main RC Oscillator Calibration Bits for 8 MHz
    SEL8 OFFSET(15) NUMBITS(1) [],
    /// Main RC Oscillator Calibration Bits for 12 MHz
    CAL12 OFFSET(16) NUMBITS(7) [],
    /// Selection of Main RC Oscillator Calibration Bits for 12 MHz
    SEL12 OFFSET(23) NUMBITS(1) []
],
SLPWK_ER0 [
    /// Peripheral 7 SleepWalking Enable
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 8 SleepWalking Enable
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 9 SleepWalking Enable
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 10 SleepWalking Enable
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 11 SleepWalking Enable
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 12 SleepWalking Enable
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 13 SleepWalking Enable
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 14 SleepWalking Enable
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 15 SleepWalking Enable
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 16 SleepWalking Enable
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 17 SleepWalking Enable
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 18 SleepWalking Enable
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 19 SleepWalking Enable
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 20 SleepWalking Enable
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 21 SleepWalking Enable
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 22 SleepWalking Enable
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral 23 SleepWalking Enable
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral 24 SleepWalking Enable
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 25 SleepWalking Enable
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 26 SleepWalking Enable
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 27 SleepWalking Enable
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 28 SleepWalking Enable
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral 29 SleepWalking Enable
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral 30 SleepWalking Enable
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral 31 SleepWalking Enable
    PID31 OFFSET(31) NUMBITS(1) []
],
SLPWK_DR0 [
    /// Peripheral 7 SleepWalking Disable
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 8 SleepWalking Disable
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 9 SleepWalking Disable
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 10 SleepWalking Disable
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 11 SleepWalking Disable
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 12 SleepWalking Disable
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 13 SleepWalking Disable
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 14 SleepWalking Disable
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 15 SleepWalking Disable
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 16 SleepWalking Disable
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 17 SleepWalking Disable
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 18 SleepWalking Disable
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 19 SleepWalking Disable
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 20 SleepWalking Disable
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 21 SleepWalking Disable
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 22 SleepWalking Disable
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral 23 SleepWalking Disable
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral 24 SleepWalking Disable
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 25 SleepWalking Disable
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 26 SleepWalking Disable
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 27 SleepWalking Disable
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 28 SleepWalking Disable
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral 29 SleepWalking Disable
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral 30 SleepWalking Disable
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral 31 SleepWalking Disable
    PID31 OFFSET(31) NUMBITS(1) []
],
SLPWK_SR0 [
    /// Peripheral 7 SleepWalking Status
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 8 SleepWalking Status
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 9 SleepWalking Status
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 10 SleepWalking Status
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 11 SleepWalking Status
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 12 SleepWalking Status
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 13 SleepWalking Status
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 14 SleepWalking Status
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 15 SleepWalking Status
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 16 SleepWalking Status
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 17 SleepWalking Status
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 18 SleepWalking Status
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 19 SleepWalking Status
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 20 SleepWalking Status
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 21 SleepWalking Status
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 22 SleepWalking Status
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral 23 SleepWalking Status
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral 24 SleepWalking Status
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 25 SleepWalking Status
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 26 SleepWalking Status
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 27 SleepWalking Status
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 28 SleepWalking Status
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral 29 SleepWalking Status
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral 30 SleepWalking Status
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral 31 SleepWalking Status
    PID31 OFFSET(31) NUMBITS(1) []
],
SLPWK_ASR0 [
    /// Peripheral 7 Activity Status
    PID7 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 8 Activity Status
    PID8 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 9 Activity Status
    PID9 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 10 Activity Status
    PID10 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 11 Activity Status
    PID11 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 12 Activity Status
    PID12 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 13 Activity Status
    PID13 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 14 Activity Status
    PID14 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 15 Activity Status
    PID15 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 16 Activity Status
    PID16 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 17 Activity Status
    PID17 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 18 Activity Status
    PID18 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 19 Activity Status
    PID19 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 20 Activity Status
    PID20 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 21 Activity Status
    PID21 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 22 Activity Status
    PID22 OFFSET(22) NUMBITS(1) [],
    /// Peripheral 23 Activity Status
    PID23 OFFSET(23) NUMBITS(1) [],
    /// Peripheral 24 Activity Status
    PID24 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 25 Activity Status
    PID25 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 26 Activity Status
    PID26 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 27 Activity Status
    PID27 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 28 Activity Status
    PID28 OFFSET(28) NUMBITS(1) [],
    /// Peripheral 29 Activity Status
    PID29 OFFSET(29) NUMBITS(1) [],
    /// Peripheral 30 Activity Status
    PID30 OFFSET(30) NUMBITS(1) [],
    /// Peripheral 31 Activity Status
    PID31 OFFSET(31) NUMBITS(1) []
],
PMMR [
    /// PLLA Maximum Allowed Multiplier Value
    PLLA_MMAX OFFSET(0) NUMBITS(11) []
],
SLPWK_ER1 [
    /// Peripheral 32 SleepWalking Enable
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral 33 SleepWalking Enable
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral 34 SleepWalking Enable
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral 35 SleepWalking Enable
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral 37 SleepWalking Enable
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral 39 SleepWalking Enable
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 40 SleepWalking Enable
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 41 SleepWalking Enable
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 42 SleepWalking Enable
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 43 SleepWalking Enable
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 44 SleepWalking Enable
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 45 SleepWalking Enable
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 46 SleepWalking Enable
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 47 SleepWalking Enable
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 48 SleepWalking Enable
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 49 SleepWalking Enable
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 50 SleepWalking Enable
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 51 SleepWalking Enable
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 52 SleepWalking Enable
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 53 SleepWalking Enable
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 56 SleepWalking Enable
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 57 SleepWalking Enable
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 58 SleepWalking Enable
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 59 SleepWalking Enable
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 60 SleepWalking Enable
    PID60 OFFSET(28) NUMBITS(1) []
],
SLPWK_DR1 [
    /// Peripheral 32 SleepWalking Disable
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral 33 SleepWalking Disable
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral 34 SleepWalking Disable
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral 35 SleepWalking Disable
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral 37 SleepWalking Disable
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral 39 SleepWalking Disable
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 40 SleepWalking Disable
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 41 SleepWalking Disable
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 42 SleepWalking Disable
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 43 SleepWalking Disable
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 44 SleepWalking Disable
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 45 SleepWalking Disable
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 46 SleepWalking Disable
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 47 SleepWalking Disable
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 48 SleepWalking Disable
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 49 SleepWalking Disable
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 50 SleepWalking Disable
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 51 SleepWalking Disable
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 52 SleepWalking Disable
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 53 SleepWalking Disable
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 56 SleepWalking Disable
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 57 SleepWalking Disable
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 58 SleepWalking Disable
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 59 SleepWalking Disable
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 60 SleepWalking Disable
    PID60 OFFSET(28) NUMBITS(1) []
],
SLPWK_SR1 [
    /// Peripheral 32 SleepWalking Status
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral 33 SleepWalking Status
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral 34 SleepWalking Status
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral 35 SleepWalking Status
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral 37 SleepWalking Status
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral 39 SleepWalking Status
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 40 SleepWalking Status
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 41 SleepWalking Status
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 42 SleepWalking Status
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 43 SleepWalking Status
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 44 SleepWalking Status
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 45 SleepWalking Status
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 46 SleepWalking Status
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 47 SleepWalking Status
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 48 SleepWalking Status
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 49 SleepWalking Status
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 50 SleepWalking Status
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 51 SleepWalking Status
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 52 SleepWalking Status
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 53 SleepWalking Status
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 56 SleepWalking Status
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 57 SleepWalking Status
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 58 SleepWalking Status
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 59 SleepWalking Status
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 60 SleepWalking Status
    PID60 OFFSET(28) NUMBITS(1) []
],
SLPWK_ASR1 [
    /// Peripheral 32 Activity Status
    PID32 OFFSET(0) NUMBITS(1) [],
    /// Peripheral 33 Activity Status
    PID33 OFFSET(1) NUMBITS(1) [],
    /// Peripheral 34 Activity Status
    PID34 OFFSET(2) NUMBITS(1) [],
    /// Peripheral 35 Activity Status
    PID35 OFFSET(3) NUMBITS(1) [],
    /// Peripheral 37 Activity Status
    PID37 OFFSET(5) NUMBITS(1) [],
    /// Peripheral 39 Activity Status
    PID39 OFFSET(7) NUMBITS(1) [],
    /// Peripheral 40 Activity Status
    PID40 OFFSET(8) NUMBITS(1) [],
    /// Peripheral 41 Activity Status
    PID41 OFFSET(9) NUMBITS(1) [],
    /// Peripheral 42 Activity Status
    PID42 OFFSET(10) NUMBITS(1) [],
    /// Peripheral 43 Activity Status
    PID43 OFFSET(11) NUMBITS(1) [],
    /// Peripheral 44 Activity Status
    PID44 OFFSET(12) NUMBITS(1) [],
    /// Peripheral 45 Activity Status
    PID45 OFFSET(13) NUMBITS(1) [],
    /// Peripheral 46 Activity Status
    PID46 OFFSET(14) NUMBITS(1) [],
    /// Peripheral 47 Activity Status
    PID47 OFFSET(15) NUMBITS(1) [],
    /// Peripheral 48 Activity Status
    PID48 OFFSET(16) NUMBITS(1) [],
    /// Peripheral 49 Activity Status
    PID49 OFFSET(17) NUMBITS(1) [],
    /// Peripheral 50 Activity Status
    PID50 OFFSET(18) NUMBITS(1) [],
    /// Peripheral 51 Activity Status
    PID51 OFFSET(19) NUMBITS(1) [],
    /// Peripheral 52 Activity Status
    PID52 OFFSET(20) NUMBITS(1) [],
    /// Peripheral 53 Activity Status
    PID53 OFFSET(21) NUMBITS(1) [],
    /// Peripheral 56 Activity Status
    PID56 OFFSET(24) NUMBITS(1) [],
    /// Peripheral 57 Activity Status
    PID57 OFFSET(25) NUMBITS(1) [],
    /// Peripheral 58 Activity Status
    PID58 OFFSET(26) NUMBITS(1) [],
    /// Peripheral 59 Activity Status
    PID59 OFFSET(27) NUMBITS(1) [],
    /// Peripheral 60 Activity Status
    PID60 OFFSET(28) NUMBITS(1) []
],
SLPWK_AIPR [
    /// Activity In Progress
    AIP OFFSET(0) NUMBITS(1) []
],
PCK[0] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[1] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[2] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[3] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[4] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[5] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[6] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
],
PCK[7] [
    /// Programmable Clock Source Selection
    CSS OFFSET(0) NUMBITS(3) [
        /// SLCK is selected
        SLCKIsSelected = 0,
        /// MAINCK is selected
        MAINCKIsSelected = 1,
        /// PLLACK is selected
        PLLACKIsSelected = 2,
        /// UPLLCKDIV is selected
        UPLLCKDIVIsSelected = 3,
        /// MCK is selected
        MCKIsSelected = 4
    ],
    /// Programmable Clock Prescaler
    PRES OFFSET(4) NUMBITS(8) []
]
];
const PMC_BASE: StaticRef<PmcRegisters> =
    unsafe { StaticRef::new(0x400E0600 as *const PmcRegisters) };

// End autogenerated block
////////////////////////////////////////////////////////////////////////////////

